name: Black

on: push

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Black
        uses: psf/black@stable
